Bash scripts to initialize the project
polylang/wp-phpunit pull request #1
Opened 2021-08-10 12:05 UTC by Screenfeed

## Scripts to install the WordPress test suite
A php script has been added, allowing to fix a compatibility issue with the tests suite: it does a text replacement in a file to make a method compatiblie with the one it extends.

## Scripts to install the required plugins and themes.
Functions have been added to easy plugins and themes installations.

## Scripts for building and distributing the project
Basically the same things already present in Polylang, but with some parameters.

2021-08-10 12:15 UTC, Screenfeed commented
@Chouby We probably want to do something about the composer scripts `install-suite` and `install-suite-nodb`, as it may not work for everybody :(
Any thoughts?

2021-08-16 13:08 UTC, Chouby requested changes

2021-08-18 09:38 UTC, Screenfeed commented on bin/build.sh
> +fi
Done in a739479.

2021-08-18 09:39 UTC, Screenfeed commented on bin/distribute.sh
> +fi
Done in a739479.

2021-08-18 09:42 UTC, Screenfeed commented on bin/distribute.sh
> +rm -rf "$1/"
Yes it's possible. For `polylang/polylang-pro` it will be `polylang-pro.zip` for example. The caveat is for projects like this one: it will be `wp-phpunit.zip`, so a parameter can be used to customize this into `polylang-phpunit.zip` for example.
Done in a739479.

2021-08-18 09:42 UTC, Screenfeed commented on bin/install-wp-tests.sh
> +installDb
Done in a739479.

2021-08-31 10:06 UTC, Chouby requested changes
For the file `install-wp-tests.sh`, I propose to use directly the latest version of the original file available https://github.com/wp-cli/scaffold-command/blob/master/templates/install-wp-tests.sh

2021-08-31 10:18 UTC, Screenfeed commented
Done in 1f113e8.

2021-09-06 13:32 UTC, merged