Bootstraps and helpers for phpunit
polylang/wp-phpunit pull request #2
Opened 2021-08-10 13:19 UTC by Screenfeed

- Created bootstraps for unit and integration tests.
- Created a trait containing helpers. Most of them allow to work with Reflexions.
- Added Brain\Monkey for unit tests.
- Added a way to mock the most used WordPress functions in unit tests.

2021-08-12 15:07 UTC, Screenfeed commented
I am also considering adding this to `Integration\AbstractTestCase`:
```php
abstract class AbstractTestCase extends WP_UnitTestCase {

	/**
	 * @var string[]
	 */
	protected static $locales = array(
		'en' => 'en_US',
		'fr' => 'fr_FR',
		'de' => 'de_DE_formal',
	);

	/**
	 * Initialization before all tests run.
	 *
	 * @param  WP_UnitTest_Factory $factory WP_UnitTest_Factory object.
	 * @return void
	 */
	public static function wpSetUpBeforeClass( WP_UnitTest_Factory $factory ) {
		// ...

		array_map( [ __CLASS__, 'createLanguage' ], static::$locales );
	}
}
```

It creates languages by default, as I believe this is needed in all our integration tests. And we only need to override the `$locales` property to modify this behavior.

2021-08-17 09:12 UTC, Chouby requested changes

2021-08-17 09:12 UTC, Chouby commented on UnitTests/Integration/bootstrap.php
> +	$pllaiTestBootstrap->initTestSuite();
I would rather not use the `pllai` prefix in this package (found in other places too).

2021-08-18 09:45 UTC, Screenfeed commented on UnitTests/Bootstrap.php
> +					'Unit Tests for Polylang for WP All Import require PHP %s or higher.',
Indeed, another copy/paste drama.

2021-08-18 10:17 UTC, Screenfeed commented on UnitTests/Integration/bootstrap.php
> +	$pllaiTestBootstrap->initTestSuite();
Of course 😅

2021-08-18 11:57 UTC, Screenfeed commented on UnitTests/Integration/AbstractTestCase.php
> +abstract class AbstractTestCase extends WP_UnitTestCase {
1- I assumed it is used all the time, for all our tests. Am I wrong?
2- Shorter to use.
With a trait we would have something like that:
```php
use WP_Syntex\Polylang_Phpunit\Integration\TestCaseTrait;

class PLL_FoobarUnitTestCase extends WP_UnitTestCase {
	use TestCaseTrait;
}
```

With an abstract class:
```php
use WP_Syntex\Polylang_Phpunit\Integration\AbstractTestCase;

class PLL_FoobarUnitTestCase extends AbstractTestCase {
	// Nothing here.
}
```
3- Even if traits are not that bad, we should avoid them when possible (ok, we can say the same for inheritance 😅).

On the other hand, I just saw that Polylang's tests can extend different abstract TestCase classes, like `WP_UnitTestCase`, `WP_Ajax_UnitTestCase`, `WP_Canonical_UnitTestCase`. So I guess we have no other choices than using a trait.

2021-08-18 12:51 UTC, Screenfeed commented on UnitTests/Unit/AbstractTestCase.php
> +				'_nx',
I wasn't aware of this package.

Since it also installs `yoast/phpunit-polyfills` and seems to require some changes in our suite, I suggest not to use it yet, I think it's better to wait for the WP team's communication.

For now I can suggest 2 ways:
1- Copy/paste the part you highlighted.
2- Not include `Brain/Monkey` in our suite, but only at the project level: on second thought, it is not widely used in our projects, so it will be useless most of the time.

What do you think @Chouby?

2021-08-18 13:12 UTC, Screenfeed commented on UnitTests/Integration/bootstrap.php
> +			}
This was to trigger callbacks registered with `register_activation_hook()`.
I remember needing this at some point, but removing it doesn't seem to break anything now 🤔
I'll remove it for now and see what happens.

2021-08-18 13:20 UTC, Screenfeed commented on UnitTests/Integration/bootstrap.php
> +function initWoocommerce( $pluginsDir ) {
You mean the things from [here](https://github.com/polylang/polylang-wc/tree/master/tests/phpunit/includes)?

2021-08-18 13:42 UTC, Screenfeed commented on UnitTests/Bootstrap.php
> +					'Unit Tests for Polylang for WP All Import require PHP %s or higher.',
Fixed in 884ea15.

2021-08-18 13:43 UTC, Screenfeed commented on UnitTests/Integration/AbstractTestCase.php
> +abstract class AbstractTestCase extends WP_UnitTestCase {
Done in 884ea15.

2021-08-18 13:44 UTC, Screenfeed commented on UnitTests/Integration/bootstrap.php
> +			}
Done in 884ea15.

2021-08-18 13:44 UTC, Screenfeed commented on UnitTests/Integration/bootstrap.php
> +	$pllaiTestBootstrap->initTestSuite();
Fixed in 884ea15.

2021-08-19 08:18 UTC, Screenfeed commented on UnitTests/Unit/AbstractTestCase.php
> +				'_nx',
OK, so we keep it.

2021-08-19 10:08 UTC, Screenfeed commented on UnitTests/Integration/bootstrap.php
> +function initWoocommerce( $pluginsDir ) {
Done in f7ff74b.

Note that I didn't include everything: after inspecting the class, half of it is PLLWC specific or already in this suite.

2021-09-07 13:54 UTC, merged