Linters
polylang/wp-phpunit pull request #3
Opened 2021-08-10 13:46 UTC by Screenfeed

Requires #1 and #2 to be merged.

## PHPCS for our projects
- This adds custom sniffs to enforce our conventions.
- This adds Suin (for PSR-4), and WordPress (some sniffs are removed).
- Those sniffs can be used in our projects.

## PHPStan for our projects
Stubs have been added (composer require) and can be used directly in our projects without the need to add them to the project's `composer.json`.

## PHPCS and PHPStan for this project
PHPCS and PHPStan have been added to lint this project.

2021-09-09 11:52 UTC, Chouby requested changes

2021-09-09 11:52 UTC, Chouby commented on phpcs.xml.dist
> +		<exclude name="Squiz.PHP.CommentedOutCode.Found"/>
I don't believe that we need to exlude this sniff.

2021-09-09 11:52 UTC, Chouby commented on phpcs.xml.dist
> +		<exclude name="WordPress.PHP.DiscouragedPHPFunctions.serialize_serialize"/>
Same as above.

2021-09-09 11:52 UTC, Chouby commented on phpcs.xml.dist
> +<ruleset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="Polylang WPAI" xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/squizlabs/PHP_CodeSniffer/master/phpcs.xsd">
Not Polylang WPAI.

2021-09-09 11:52 UTC, Chouby commented on phpcs.xml.dist
> +	<rule ref="Squiz.WhiteSpace.ControlStructureSpacing.NoLineAfterClose"/>
Why using custom sniffs not in `polylang-cs` ?

2021-09-09 11:52 UTC, Chouby commented on composer.json
> +		"php-stubs/woocommerce-stubs": "^5.5",
What do you think to use `*` for the WC stubs? With one update per month, it can become very teious to be up to date.

2021-09-09 11:54 UTC, Chouby requested changes
Could you update composer.lock. I strangely experienced a fatal error while running PHPCS due to lack of files in phpstan package, solved by updating composer.

2021-09-09 14:10 UTC, Screenfeed commented on UnitTests/Unit/AbstractTestCase.php
> +				'_n'           => static function ( $single, $plural, $number ) {
Weird, I already fixed this and I have this space character locally :|

2021-09-09 14:15 UTC, Screenfeed commented on phpcs.xml.dist
> +	<rule ref="Squiz.WhiteSpace.ControlStructureSpacing.NoLineAfterClose"/>
Those are rules we didn't discussed during our meetings since we focused only on naming conventions.
Should I remove them or include them in our coding standards?

2021-09-09 14:22 UTC, Screenfeed commented on composer.json
> +		"php-stubs/woocommerce-stubs": "^5.5",
Done in 63dc174.

2021-09-09 14:23 UTC, Screenfeed commented on phpcs.xml.dist
> +<ruleset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="Polylang WPAI" xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/squizlabs/PHP_CodeSniffer/master/phpcs.xsd">
Fixed in 63dc174 🙄

2021-09-09 14:23 UTC, Screenfeed commented on phpcs.xml.dist
> +		<exclude name="WordPress.PHP.DiscouragedPHPFunctions.serialize_serialize"/>
Removed in 63dc174.

2021-09-09 14:24 UTC, Screenfeed commented on phpcs.xml.dist
> +		<exclude name="Squiz.PHP.CommentedOutCode.Found"/>
Removed in 63dc174 (I usually exclude it because it triggers false positives most of the time).

2021-09-09 14:24 UTC, Screenfeed commented on UnitTests/Bootstrap.php
> +
Fixed my mess in 63dc174.

2021-09-09 14:29 UTC, Screenfeed commented on UnitTests/Unit/AbstractTestCase.php
> +				'_n'           => static function ( $single, $plural, $number ) {
Anyway, it's fixed.

2021-09-10 09:09 UTC, Screenfeed commented on phpcs.xml.dist
> +	<rule ref="Squiz.WhiteSpace.ControlStructureSpacing.NoLineAfterClose"/>
Removed in a9226dc.

2021-09-10 11:39 UTC, merged