Compatibility with Yoast's polyfills and utils
polylang/wp-phpunit pull request #6
Opened 2021-10-19 15:33 UTC by Screenfeed

Note: the version for `wpsyntex/polylang-cs` is temporarily set to `dev-new-allow-tests-setup-methods`. It needs to be reverted to `dev-main` before merging.

Require the right dependencies:
- The project now requires [yoast/wp-test-utils](https://github.com/Yoast/wp-test-utils).
- `brain/monkey` has been removed, since it is already required by `yoast/wp-test-utils`.
- Version for `phpunit/phpunit` is now `^5.7.21 || ^6.5 || ^7.5`: the versions > 7.5 are causing problems from php 5.6 to 8.0.
- Added scripts `install-suite` and `install-suite-with-db`: the test suite is required for phpstan to work.

New bash function downloadWoocommerce(): this allows to download the plugin from git, with its test suite.

Define the constant `WP_TESTS_PHPUNIT_POLYFILLS_PATH`.

Improved unit tests (`AbstractTestCase`):
- Use `Yoast\WPTestUtils\BrainMonkey\YoastTestCase` as base class instead of `PHPUnit\Framework\TestCase`.
- Rename the `setUp*()` functions in snake_case.
- Replace the static property `$mockCommonWpFunctionsInSetUp` by `$stubTranslationFunctions` and `$stubEscapeFunctions`. Remove the method `mockCommonWpFunctions()` (Yoast provides its own methods).

Bootstrap for unit tests: new `WP_Syntex\Polylang_Phpunit\Unit\bootstrapSuite()` function for concistency with integration tests.

Improved integration tests (`TestCaseTrait` ): rename the `setUp*()` functions in snake_case. Also removed the `WP_UnitTest_Factory` parameter to be compatible with the parent class.

Bootstrap for integration tests:
- Changed the order of the parameters of `WP_Syntex\Polylang_Phpunit\Integration\bootstrapSuite()`:
  - The plugins list is now the 3rd parameter: this is to have the same parameters order than the same function from the unit tests.
  - It is now an entry of a more generic `$args` parameter: better if we need more parameters later.

2021-10-21 06:37 UTC, Chouby requested changes

2021-10-21 08:10 UTC, Screenfeed commented on UnitTests/Integration/TestCaseTrait.php
> +	public static function tear_down_after_class() {
Damn, I forgot to revert this one.

2021-10-21 08:11 UTC, Screenfeed commented on UnitTests/Unit/bootstrap.php
> + * Bootstraps the PLL AI unit tests
Another copy-paste drama 😅

2021-10-21 09:57 UTC, Screenfeed commented on UnitTests/Integration/TestCaseTrait.php
> +	public static function tear_down_after_class() {
Done in 8728c8f.

2021-10-21 09:57 UTC, Screenfeed commented on UnitTests/Unit/bootstrap.php
> + * Bootstraps the PLL AI unit tests
Done in ba1523c.

2021-10-21 09:58 UTC, Screenfeed commented on bin/wp-download-tools.sh
> +downloadWoocommerce() {
Done in 23d5b25.

2021-10-21 09:58 UTC, Screenfeed commented on composer.json
> +		"phpunit/phpunit": "^5.7.21 || ^6.5 || ^7.5",
Done in f5b88be.

2021-10-21 13:42 UTC, Screenfeed commented on bin/wp-download-tools.sh
> +downloadWoocommerce() {
Improved in 1ecccb6.

2021-11-02 15:25 UTC, Chouby requested changes

2021-11-02 15:25 UTC, Chouby commented on README.md
> +class Barbaz extends AbstractTestCase {$$
`$$` Is it a typo?

2021-11-02 15:36 UTC, merged